services:
  backend:
    build: ./InsightApps
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    # command: python /app/manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./InsightApps-Angular
    ports:
      - "8080:80"
    volumes:
      - ./dist/InsightApps-Angular:/frontend:/usr/share/nginx/html


