services:
  backend:
    build: ./InsightApps
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    # command: python /app/manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./InsightApps-Angular
    ports:
      - "8080:80"
    volumes:
      - ./dist/InsightApps-Angular:/frontend:/usr/share/nginx/html


# # version: '3.8'

# services:
#   backend:
#     build:
#       context: .
#       dockerfile: dockerfile.InsightApps
#     container_name: django-backend
#     volumes:
#       - ./backend:/app
#     ports:
#       - "8000:8000"
#     networks:
#       - project-network
#     depends_on:
#       - frontend

#   frontend:
#     build:
#       context: .
#       dockerfile: dockerfile.InsightApps-Angular
#     container_name: angular-frontend
#     volumes:
#       - ./frontend:/app
#     ports:
#       - "80:80"
#     networks:
#       - project-network

# networks:
#   project-network:
#     driver: bridge
