# Generated by Django 4.1.13 on 2024-07-31 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0007_alter_tokenstoring_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenstoring',
            name='parameter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tokenstoring',
            name='salesuserid',
            field=models.CharField(blank=True, db_column='salesforce_user_id', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tokenstoring',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 16, 23, 12, 366404)),
        ),
        migrations.AlterField(
            model_name='tokenstoring',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 17, 23, 12, 366404)),
        ),
        migrations.AlterField(
            model_name='tokenstoring',
            name='qbuserid',
            field=models.CharField(blank=True, db_column='quickbooks_user_id', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tokenstoring',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 16, 23, 12, 366404)),
        ),
    ]
