"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$!va8pxb&5j9%67x)8t1&zr_xa@w+c@kteqeat!r2(94#s=pf$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost','50.18.24.167']

AUTH_USER_MODEL = "dashboard.UserProfile"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
    'quickbooks',
    'copilot',
    
    'rest_framework',
    'rest_framework.authtoken',
    'knox',
    'corsheaders',
    'oauth2_provider',
    'drf_yasg',
]


# Email Configrations
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'pakshay@stratapps.com' # Add Authorized Email
EMAIL_HOST_PASSWORD = 'AKShay@stratapps' #Add Authorized Password


# If you want to allow access for all domains, set the following variable to TRUE
CORS_ORIGIN_ALLOW_ALL = True

CORS_ORIGIN_WISHLIST = [
    'http://localhost:4200',
    'http://127.0.0.1:5000',
    'http://127.0.0.1:8000',
    '*',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    #CORS MiddleWare
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
   'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'insightapps',
        'USER': 'postgres',
        'PASSWORD': 'Welcome!234',
        'HOST': 'e-commerce.cj3oddyv0bsk.us-west-1.rds.amazonaws.com',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SECURE_CROSS_ORIGIN_OPENER_POLICY=None

# Value determines whether the server allows cookies in the cross-site HTTP requests
CORS_ALLOW_CREDENTIALS = True

# Methods allowed for CORS
CORS_ALLOW_METHODS = [
    'DELETE',
    'OPTIONS',
    'PATCH',
    'GET',
    'POST',
    'PUT',  
]

# Non-standard headers allowed in the request
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]



expiry_time=datetime.datetime.now()+datetime.timedelta(seconds=3600)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ),
}

AWS_S3_ACCESS_KEY_ID = 'AKIA4RCTO2E4PTFUDX2B'
AWS_S3_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'haskmedia'
AWS_S3_REGION_NAME = 'us-east-1' 


SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
}

perpage = 10  ## for pagination

db_connections=10

ENVIRONMENT = 'sandbox'

SANDBOX_URL = 'https://sandbox-quickbooks.api.intuit.com'
SANDBOX_QUICKBOOKS_ID = 'ABN3bfKZ83th7PXGXAXNo1yvROLrImX3lLT5ntMKDtDYefyanc'
SANDBOX_QUICKBOOKS_SECRET = '7cGjESdGMpKXRuPAurZ46lZ4xKcAqi7RxR4FJcwc'
SANDBOX_REDIRECT_URL = 'https://www.google.com/' #### change with https://domain redirection path
SANDBOX_SCOPES = ['com.intuit.quickbooks.accounting','com.intuit.quickbooks.payment','openid','profile','email','phone','address']
token_url='https://www.google.com/'

link_url = 'http://localhost:8000/'

#######  oauth2  #######
CLIENT_ID = 'IBQBcMjZnAJYfiUdXQNZzyslEfIqn6cHPgS6FwVz'
CLIENT_SECRET = 'L2y3hqwtdNycJBGvOkBWvh6lrkuTcDOD'
TOKEN_URL = 'http://localhost:8000/v1/oauth2/token/'


OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 57600,  # Access token expiration time (in seconds)
    'REFRESH_TOKEN_EXPIRE_SECONDS': 86400,  # Refresh token expiration time (in seconds)
}


SALESFORCE_CONSUMER_KEY = '3MVG9GCMQoQ6rpzRBaREKELslW7uprKCSg.QA7B9zh4w9rU_SeFrjLAYlqM2mN9JfPuVr4q30x_yOT0Ix7x2W'
SALESFORCE_CONSUMER_SECRET = '5ABD2809EF21B2F104B3BD4CB47793200A134FF6A19D102B3F90A799F43DB67F'
# SALESFORCE_REDIRECT_URI = 'https://hask.io/lander'
SALESFORCE_REDIRECT_URI = 'http://localhost:8000/v1/callback/'
SALESFORCE_AUTH_URL = 'https://stratapps6-dev-ed.develop.my.salesforce.com/services/oauth2/authorize'
SALESFORCE_TOKEN_URL = 'https://stratapps6-dev-ed.develop.my.salesforce.com/services/oauth2/token'