# Generated by Django 5.0.4 on 2024-05-02 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_account_activation_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetails',
            fields=[
                ('id', models.AutoField(db_column='file_details_id', primary_key=True, serialize=False)),
                ('file_type', models.PositiveBigIntegerField(db_column='file_type_id')),
                ('source', models.CharField(blank=True, db_column='source_path', max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime(2024, 5, 2, 16, 4, 30, 95871))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.PositiveBigIntegerField(db_column='user_id')),
            ],
            options={
                'db_table': 'file_details',
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(db_column='file_type_id', primary_key=True, serialize=False)),
                ('file_type', models.CharField(db_column='file_type', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'file_type',
            },
        ),
        migrations.CreateModel(
            name='ServerDetails',
            fields=[
                ('id', models.AutoField(db_column='server_details_id', primary_key=True, serialize=False)),
                ('server_type', models.PositiveBigIntegerField(db_column='server_type_id')),
                ('hostname', models.CharField(db_column='hostname', max_length=500, null=True)),
                ('username', models.CharField(db_column='username', max_length=500, null=True)),
                ('password', models.CharField(db_column='password', max_length=500, null=True)),
                ('database', models.CharField(db_column='database', max_length=500, null=True)),
                ('service_name', models.CharField(db_column='service_name', max_length=500, null=True)),
                ('port', models.IntegerField(db_column='port', null=True)),
                ('user_id', models.IntegerField(db_column='user_id', null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 5, 2, 16, 4, 30, 95871))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'server_details',
            },
        ),
        migrations.CreateModel(
            name='ServerType',
            fields=[
                ('id', models.AutoField(db_column='server_type_id', primary_key=True, serialize=False)),
                ('server_type', models.CharField(db_column='server_type', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'server_type',
            },
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 16, 4, 30, 93842)),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 16, 4, 30, 93842)),
        ),
        migrations.AlterField(
            model_name='reset_password',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 16, 4, 30, 94840)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 16, 4, 30, 90851)),
        ),
    ]
