# Generated by Django 5.0.4 on 2024-05-02 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_filedetails_filetype_serverdetails_servertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedetails',
            name='display_name',
            field=models.CharField(db_column='display_name', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='serverdetails',
            name='display_name',
            field=models.CharField(db_column='display_name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 17, 36, 10, 738641)),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 17, 36, 10, 738641)),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 17, 36, 10, 739638)),
        ),
        migrations.AlterField(
            model_name='reset_password',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 17, 36, 10, 738641)),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 17, 36, 10, 740635)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 2, 17, 36, 10, 735648)),
        ),
    ]
