# Generated by Django 5.0.4 on 2024-05-15 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_querysets_delete_queryset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartFilters',
            fields=[
                ('filter_id', models.AutoField(db_column='filter_id', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('server_id', models.IntegerField()),
                ('queryset_id', models.IntegerField()),
                ('schema', models.CharField(max_length=500)),
                ('table_name', models.CharField(max_length=500)),
                ('col_name', models.CharField(max_length=500)),
                ('data_type', models.CharField(max_length=500)),
                ('filter_data', models.TextField()),
                ('format_type', models.CharField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 5, 15, 15, 48, 47, 871742))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chart_filters',
            },
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 15, 48, 47, 856774)),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 15, 48, 47, 856774)),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 15, 48, 47, 858770)),
        ),
        migrations.AlterField(
            model_name='querysets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 15, 48, 47, 871742)),
        ),
        migrations.AlterField(
            model_name='reset_password',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 15, 48, 47, 856774)),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 15, 48, 47, 858770)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 15, 48, 47, 853746)),
        ),
    ]
