# Generated by Django 5.0.4 on 2024-05-21 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_account_activation_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(max_length=500)),
                ('min_measures', models.CharField(default=0, max_length=500)),
                ('max_measures', models.CharField(max_length=500)),
                ('min_dimensions', models.CharField(default=0, max_length=500)),
                ('max_dimensions', models.CharField(max_length=500)),
                ('min_dates', models.CharField(default=0, max_length=500)),
                ('max_dates', models.CharField(max_length=500)),
                ('min_geo', models.CharField(default=0, max_length=500)),
                ('max_geo', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'charts',
            },
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 14, 49, 34, 710246)),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 14, 49, 34, 710246)),
        ),
        migrations.AlterField(
            model_name='chartfilters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 14, 49, 34, 710246)),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 14, 49, 34, 710246)),
        ),
        migrations.AlterField(
            model_name='functions_tb',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 14, 49, 34, 710246)),
        ),
        migrations.AlterField(
            model_name='querysets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 14, 49, 34, 710246)),
        ),
        migrations.AlterField(
            model_name='reset_password',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 14, 49, 34, 710246)),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 14, 49, 34, 710246)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 14, 49, 34, 710246)),
        ),
    ]
