# Generated by Django 5.0.4 on 2024-05-21 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_charts_alter_account_activation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_activation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 15, 1, 10, 358888)),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 23, 15, 1, 10, 358888)),
        ),
        migrations.AlterField(
            model_name='chartfilters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 15, 1, 10, 373908)),
        ),
        migrations.AlterField(
            model_name='charts',
            name='chart_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='charts',
            name='max_dates',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='charts',
            name='max_dimensions',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='charts',
            name='max_geo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='charts',
            name='max_measures',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='charts',
            name='min_dates',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='charts',
            name='min_dimensions',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='charts',
            name='min_geo',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='charts',
            name='min_measures',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 15, 1, 10, 358888)),
        ),
        migrations.AlterField(
            model_name='functions_tb',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 15, 1, 10, 373908)),
        ),
        migrations.AlterField(
            model_name='querysets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 15, 1, 10, 373908)),
        ),
        migrations.AlterField(
            model_name='reset_password',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 15, 1, 10, 358888)),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 15, 1, 10, 358888)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 15, 1, 10, 358888)),
        ),
    ]
