# Generated by Django 5.0.4 on 2024-05-30 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_account_activation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartfilters',
            name='alias',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 12, 16, 32, 35456)),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 1, 12, 16, 32, 35456)),
        ),
        migrations.AlterField(
            model_name='chartfilters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 12, 16, 32, 48453)),
        ),
        migrations.AlterField(
            model_name='chartfilters',
            name='format_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 12, 16, 32, 37454)),
        ),
        migrations.AlterField(
            model_name='functions_tb',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 12, 16, 32, 48453)),
        ),
        migrations.AlterField(
            model_name='querysets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 12, 16, 32, 48453)),
        ),
        migrations.AlterField(
            model_name='reset_password',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 12, 16, 32, 36455)),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 12, 16, 32, 38453)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 12, 16, 32, 32454)),
        ),
    ]
