# Generated by Django 5.0.4 on 2024-06-03 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_chartfilters_alias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceFilter',
            fields=[
                ('datasource_filter_id', models.AutoField(db_column='datasource_filter_id', primary_key=True, serialize=False)),
                ('server_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('queryset_id', models.IntegerField()),
                ('tables', models.CharField(max_length=1000)),
                ('alias', models.CharField(default=[], max_length=1000)),
                ('datatype', models.CharField(max_length=1000)),
                ('columns', models.CharField(max_length=1000)),
                ('custom_selected_data', models.CharField(max_length=1000)),
                ('filter_type', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 3, 13, 58, 38, 85668))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'datasource_filters',
            },
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 13, 58, 38, 68710)),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 13, 58, 38, 68710)),
        ),
        migrations.AlterField(
            model_name='chartfilters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 13, 58, 38, 84669)),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 13, 58, 38, 82675)),
        ),
        migrations.AlterField(
            model_name='functions_tb',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 13, 58, 38, 84669)),
        ),
        migrations.AlterField(
            model_name='querysets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 13, 58, 38, 83672)),
        ),
        migrations.AlterField(
            model_name='reset_password',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 13, 58, 38, 68710)),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 13, 58, 38, 83672)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 13, 58, 38, 65718)),
        ),
    ]
