# Generated by Django 4.1.13 on 2024-06-10 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_datasourcefilter_alter_account_activation_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='license_key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('key', models.CharField(db_column='License key', max_length=1500)),
                ('max_limit', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 10, 13, 57, 29, 628364))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'license_keys',
            },
        ),
        migrations.CreateModel(
            name='sheet_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('chart_id', models.IntegerField()),
                ('server_id', models.IntegerField()),
                ('queryset_id', models.IntegerField()),
                ('datapath', models.FileField(blank=True, db_column='sheet_data_path', max_length=1000, null=True, upload_to='sheetdata/')),
                ('datasrc', models.CharField(blank=True, db_column='sheet_data_source', max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 10, 13, 57, 29, 628364))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sheet_data',
            },
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 13, 57, 29, 623528)),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 13, 57, 29, 623528)),
        ),
        migrations.AlterField(
            model_name='chartfilters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 13, 57, 29, 626637)),
        ),
        migrations.AlterField(
            model_name='datasourcefilter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 13, 57, 29, 628364)),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 13, 57, 29, 625643)),
        ),
        migrations.AlterField(
            model_name='functions_tb',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 13, 57, 29, 626637)),
        ),
        migrations.AlterField(
            model_name='querysets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 13, 57, 29, 625643)),
        ),
        migrations.AlterField(
            model_name='reset_password',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 13, 57, 29, 624639)),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 13, 57, 29, 625643)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 10, 13, 57, 29, 621995)),
        ),
    ]
