# Generated by Django 4.1.13 on 2024-06-13 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_sheet_data_sheet_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashboard_data',
            fields=[
                ('id', models.AutoField(db_column='dashboard_id', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('server_id', models.IntegerField()),
                ('queryset_id', models.IntegerField()),
                ('sheet_ids', models.CharField(blank=True, max_length=1000, null=True)),
                ('dashboard_name', models.CharField(blank=True, max_length=500, null=True)),
                ('datapath', models.FileField(blank=True, db_column='dashboard_data_path', max_length=1000, null=True, upload_to='insightapps/dashboard/')),
                ('datasrc', models.CharField(blank=True, db_column='dashboard_data_source', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 51, 0, 403608))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dashboard_data',
            },
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 51, 0, 396625)),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 17, 51, 0, 396625)),
        ),
        migrations.AlterField(
            model_name='chartfilters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 51, 0, 399612)),
        ),
        migrations.AlterField(
            model_name='datasourcefilter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 51, 0, 401611)),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 51, 0, 398617)),
        ),
        migrations.AlterField(
            model_name='functions_tb',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 51, 0, 400615)),
        ),
        migrations.AlterField(
            model_name='license_key',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 51, 0, 401611)),
        ),
        migrations.AlterField(
            model_name='querysets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 51, 0, 399612)),
        ),
        migrations.AlterField(
            model_name='reset_password',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 51, 0, 397616)),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 51, 0, 399612)),
        ),
        migrations.AlterField(
            model_name='sheet_data',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 51, 0, 402611)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 17, 51, 0, 395614)),
        ),
    ]
