# Generated by Django 4.1.13 on 2024-06-19 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_datasourcefilter_queryset_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetFilter_querysets',
            fields=[
                ('Sheetqueryset_id', models.AutoField(primary_key=True, serialize=False)),
                ('datasource_querysetid', models.IntegerField(blank=True, null=True)),
                ('queryset_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(db_column='user_id')),
                ('server_id', models.IntegerField(blank=True, null=True)),
                ('filter_id_list', models.TextField(blank=True, null=True)),
                ('custom_query', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 28, 59, 589169))),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sheetFilter_querysets',
            },
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 28, 59, 583168)),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 21, 12, 28, 59, 583168)),
        ),
        migrations.AlterField(
            model_name='chartfilters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 28, 59, 586169)),
        ),
        migrations.AlterField(
            model_name='dashboard_data',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 28, 59, 588169)),
        ),
        migrations.AlterField(
            model_name='datasource_querysets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 28, 59, 586169)),
        ),
        migrations.AlterField(
            model_name='datasourcefilter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 28, 59, 587169)),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 28, 59, 585171)),
        ),
        migrations.AlterField(
            model_name='functions_tb',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 28, 59, 587169)),
        ),
        migrations.AlterField(
            model_name='license_key',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 28, 59, 588169)),
        ),
        migrations.AlterField(
            model_name='querysets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 28, 59, 586169)),
        ),
        migrations.AlterField(
            model_name='reset_password',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 28, 59, 584172)),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 28, 59, 585171)),
        ),
        migrations.AlterField(
            model_name='sheet_data',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 28, 59, 588169)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 19, 12, 28, 59, 582169)),
        ),
    ]
