# Generated by Django 4.1.13 on 2024-07-30 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_alter_account_activation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartfilters',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource_querysets',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasourcefilter',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='querysets',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sheetfilter_querysets',
            name='file_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 8, 7, 493981)),
        ),
        migrations.AlterField(
            model_name='account_activation',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 1, 12, 8, 7, 493981)),
        ),
        migrations.AlterField(
            model_name='chartfilters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 8, 7, 499980)),
        ),
        migrations.AlterField(
            model_name='chartfilters',
            name='server_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard_data',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 8, 7, 504981)),
        ),
        migrations.AlterField(
            model_name='dashboardfilters',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 8, 7, 505981)),
        ),
        migrations.AlterField(
            model_name='datasource_querysets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 8, 7, 498983)),
        ),
        migrations.AlterField(
            model_name='datasource_querysets',
            name='server_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasourcefilter',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 8, 7, 499980)),
        ),
        migrations.AlterField(
            model_name='datasourcefilter',
            name='server_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filedetails',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 8, 7, 496981)),
        ),
        migrations.AlterField(
            model_name='functions_tb',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 8, 7, 500980)),
        ),
        migrations.AlterField(
            model_name='license_key',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 8, 7, 503983)),
        ),
        migrations.AlterField(
            model_name='querysets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 8, 7, 498983)),
        ),
        migrations.AlterField(
            model_name='querysets',
            name='server_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reset_password',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 8, 7, 494981)),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 8, 7, 495980)),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 8, 7, 497980)),
        ),
        migrations.AlterField(
            model_name='sheet_data',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 8, 7, 504981)),
        ),
        migrations.AlterField(
            model_name='sheetfilter_querysets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 8, 7, 505981)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 12, 8, 7, 490983)),
        ),
    ]
