# Dockerfile for Django
FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED 1

WORKDIR /app
# Install dependencies for ODBC
RUN apt-get update && apt-get install -y \
    unixodbc \
    unixodbc-dev \
    libsqliteodbc \
    && rm -rf /var/lib/apt/lists/*
    
COPY requirements.txt /app/

# RUN pip install -r requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

ENV DJANGO_SETTINGS_MODULE=project.settings

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
